apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: argocd-quay-todo-demo-app-pipeline
  labels:
    app: todo-demo-app
  namespace: todo-demo-app
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
    - default: CHANGEME
      description: Current Image Tag Value
      name: CURRENT_IMAGE_TAG
      type: string
    - default: quay.io/takinosh/todo-demo-app:v1
      name: quay-io-repository
      type: string
    - default: latest
      name: quay-io-image-tag-name
      type: string
    - default: webhook-secret
      description: Webhook secret name
      name: webhook-secret
      type: string
  resources:
    - name: app-git
      type: git
    - name: image
      type: image
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/tosin2013/todo-demo-app'
        - name: revision
          value: master
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: fetch-helm-repository
      params:
        - name: url
          value: 'https://gitea-with-admin-gitea.apps.cluster-vcx8l.vcx8l.sandbox2835.opentlc.com/user1/todo-demo-app-helmrepo'
        - name: revision
          value: main
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: helm-output
          workspace: helm-shared-workspace
    - name: maven-run
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - '-DskipTests'
            - clean
            - package
      runAfter:
        - fetch-helm-repository
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: build-java-app-image
      params:
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: src/main/docker/Dockerfile
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/todo-demo-app/todo-demo-app:$(params.IMAGE_TAG)
        - name: TLSVERIFY
          value: 'false'
      runAfter:
        - maven-run
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: tag-test-image
      params:
        - name: SCRIPT
          value: |
            oc tag todo-demo-app:$(params.IMAGE_TAG) todo-demo-app:latest
      runAfter:
        - build-java-app-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: update-image-var-helmchart
      taskRef:
        name: sed-file
      params:
      - name: filename
        value: app/values.yaml
      - name: pattern
        value: "$(params.CURRENT_IMAGE_TAG)"
      - name: replacement
        value: "$(params.IMAGE_TAG)"
      runAfter:
        - tag-test-image
      workspaces:
      - name: source
        workspace: helm-shared-workspace
    - name: git-commit-task
      taskRef:
        name: git-commit
      params:
      - name: commit-msg
        value: "Update app/values.yaml with new image tag"
      - name: git-credentials
        value:
          secretKeyRef:
            name: git-credentials
            key: credentials
      runAfter:
        - update-image-var-helmchart
      workspaces:
      - name: source
        workspace: helm-shared-workspace
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: helm-shared-workspace