apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pipeline-sa.yaml
  - maven-source-pvc.yml
  - pvc.yml
  - git-pipeline-resource.yaml
  - git-commit.yaml
  - image-pipeline-resource.yaml
  - sed-file.yaml
  - pushImageToQuay.yaml
  - generic-deploy-pipeline.yaml
  - quay-deploy-pipeline.yaml
  - argocd-deploy-pipeline.yaml
