apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sed-file
spec:
  params:
  - default: README.md
    description: Target Filename
    name: filename
    type: string
  - default: "Hello, world!"
    description: Target pattern
    name: pattern
    type: string
  - default: "Hello, Tekton!"
    description: Target replacement
    name: replacement
    type: string
  steps:
  - name: sed
    image: alpine:3.14
    command:
    - sh
    - -c
    - |
      sed -i "s/$PATTERN/$REPLACEMENT/g" $FILENAME
    env:
    - name: FILENAME
      value: $(params.filename)
    - name: PATTERN
      value: $(params.pattern)
    - name: REPLACEMENT
      value: $(params.replacement)