apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-image-tag-in-git
  namespace: todo-demo-app
spec:
  params:
    - description: Git repository containing manifest files to update
      name: GIT_REPOSITORY
      type: string
    - default: pipeline@example.com
      name: GIT_EMAIL
      type: string
    - default: todo-demo-app
      name: GIT_NAME
      type: string
    - default: yamls/ocp
      name: GIT_MANIFEST_DIR
      type: string
    - default: quay.io/takinosh/todo-demo-app
      description: Target Registry Name
      name: TARGET_IMAGE
      type: string
    - default: v1
      description: Target TAG
      name: TARGET_TAG
      type: string
    - default: '1'
      description: Replica Count
      name: REPLICA_COUNT
      type: string
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - args:
        - '-c'
        - >
          set -eu

          git config --global user.email "$(params.GIT_EMAIL)"

          git config --global user.name "$(params.GIT_NAME)" 

          git clone --branch main --depth 1
          https://${GIT_USERNAME}:${GIT_TOKEN}@$(params.GIT_REPOSITORY) repo

          cd "repo/$(params.GIT_MANIFEST_DIR)"

          echo old value:

          yq e '.image.repository'   app/values.yaml

          yq e '.image.tag'   app/values.yaml

          yq e '.replicaCount'   app/values.yaml

          echo replacing with new values:

          echo "IMAGE_URL: $(params.TARGET_IMAGE)"

          echo "IMAGE_TAG: $(params.TARGET_TAG)"

          echo "REPLICAS: $(params.REPLICA_COUNT)"

          yq -i '.image.repository = "$(params.TARGET_IMAGE)"'
          app/values.yaml

          yq -i '.image.tag = "$(params.TARGET_TAG)"'
          app/values.yaml

          yq -i '.replicaCount = "$(params.REPLICA_COUNT)"'
          app/values.yaml

          echo verifying new values

          cat app/values.yaml

          if ! git diff-index --quiet HEAD --; then
            git status
            git add .
            git commit -m "deployment updated by tekton pipeline"
            git push
          else
              echo "no changes, git repository is up to date"
          fi
      command:
        - /bin/bash
      env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: git-infra-secret
              optional: true
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: git-infra-secret
              optional: true
      image: 'quay.io/takinosh/tekton-tools:latest'
      name: git-push
      resources: {}
  volumes:
    - emptyDir: {}
      name: varlibcontainers
    - emptyDir: {}
      name: m2-repository
