# Test chris in a box with miniChRIS-docker's test suite

name: Test Tekton Pipeline and tasks 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run-using-podman-on-Ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Test Tekton Pipeline and tasks 
        run: |
          npm --version
          npm i tekton-lint
          npm install -g tekton-lint
          #tekton-lint --help
          pwd
          cd /home/runner/work/todo-demo-app-helmrepo/todo-demo-app-helmrepo/openshift-pipelines
          ls -lath .
          tekton-lint maven-build-task.yaml